apiVersion: v1
kind: Service
metadata:
    name: "jmeterpd"
    labels:
        app: "jmeterpd"
spec:
    type: LoadBalancer
    ports:
    - port: 60000
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "jmeterpd"